bundler_args: --without development
language: ruby
rvm:
  - 2.0.0
script: bundle exec rspec
notifications:
  sqwiggle: 
    rooms:
      - secure: "j38bb0fNARwotu8i3ZGwZcMduLJqFLS/IiYXE7dGA7lR7yvt41JQGc/ANaMNJPrkaVt1jisSOZ4kMpUWJXHUt5ZO7Wmljr36NqyHA0Y3axp6EnkltpctL9G+SDYr6k3eQqcNTylQBXNU7ITlzN08CeC3p0RfUXQnPg1S2JwodO4="
